 const ActionTypes = {
     UPDATE_FLIGHTS: "UPDATE_FLIGHTS",
     UPDATE_YEAR_FILTER: "UPDATE_YEAR_FILTER",
     UPDATE_LAUNCH_FILTER: "UPDATE_LAUNCH_FILTER",
     UPDATE_LANDING_FILTER: "UPDATE_LANDING_FILTER",
}

export default ActionTypes;